ALTER TABLE abp_classification ADD FOREIGN KEY (uprn) REFERENCES abp_blpu (uprn) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE abp_crossref ADD FOREIGN KEY (uprn) REFERENCES abp_blpu (uprn) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE abp_delivery_point ADD FOREIGN KEY (uprn) REFERENCES abp_blpu (uprn) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE abp_lpi ADD FOREIGN KEY (uprn) REFERENCES abp_blpu (uprn) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE abp_organisation ADD FOREIGN KEY (uprn) REFERENCES abp_blpu (uprn) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE abp_successor ADD FOREIGN KEY (uprn) REFERENCES abp_blpu (uprn) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE abp_lpi ADD FOREIGN KEY (usrn) REFERENCES abp_street (usrn) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE abp_street_descriptor ADD FOREIGN KEY (usrn) REFERENCES abp_street (usrn) ON UPDATE NO ACTION ON DELETE NO ACTION;
